spring:
  application:
    name: anime-service
  datasource:
    url: jdbc:mysql://localhost:3306/anime_service?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${ENV_ROOT_USER:root}
    password: ${ENV_ROOT_PASSWORD:devdojo}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  threads:
    virtual:
      enabled: true
  flyway:
    enabled: true
  web:
    error:
      include-stacktrace: on_param
logging:
  level:
    academy.devdojo: debug
server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    threads:
      max: 20

management:
  server:
    port: 8989
  endpoints:
    web:
      exposure:
        include: "*"